/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    MainSection: typeof import('./src/components/Layout/MainSection.vue')['default']
    Navbar: typeof import('./src/components/Layout/Navbar.vue')['default']
    Note: typeof import('./src/components/Note/Note.vue')['default']
    NoteBox: typeof import('./src/components/Note/NoteBox.vue')['default']
    PageNotes: typeof import('./src/pages/PageNotes.vue')['default']
    PageOverview: typeof import('./src/pages/PageOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
